---
tags: [async]
projects: [spring-framework]
---
:spring_version: current
:spring_boot_version: 1.3.3.RELEASE
:jackson: http://wiki.fasterxml.com/JacksonHome
:SpringApplication: http://docs.spring.io/spring-boot/docs/{spring_boot_version}/api/org/springframework/boot/SpringApplication.html
:EnableAsync: http://docs.spring.io/spring/docs/current/spring-framework-reference/html/scheduling.html#scheduling-annotation-support
:Future: http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Future.html
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-async-method
This guide walks you through the steps to create asynchronous queries to GitHub. The focus is on the asynchronous part, a feature often used when scaling services.

== What you'll build

You'll build a lookup service that queries GitHub user information and retrieves data through GitHub's API. One approach to scaling services is to run expensive jobs in the background and wait for the results using Java's {Future}[`Future`] interface. Java's `Future` is essentially a container housed to hold the potential results. It gives you methods to let you poll if the results have arrived yet, and when they have, the ability to access the results.

== What you'll need

:java_version: 1.8
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/prereq_editor_jdk_buildtools.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]


include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-gradle.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-maven.adoc[]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/hide-show-sts.adoc[]



[[initial]]
== Create a representation of a GitHub User

Before you can create a GitHub lookup service, you need to define a representation for the data you'll retrieve through GitHub's API.

To model the user representation, you create a resource representation class. Provide a plain old Java object with fields, constructors, and accessors:

`src/main/java/hello/User.java`
[source,java]
----
include::complete/src/main/java/hello/User.java[]
----

Spring uses the {jackson}[Jackson JSON] library to convert GitHub's JSON response into a `User` object. The `@JsonIgnoreProperties` annotation signals Spring to ignore any attributes not listed in the class. This makes it easy to make REST calls and produce domain objects.

In this guide, we are only grabbing the `name` and the `blog` URL for demonstration purposes.


== Create a GitHub lookup service

Next you need to create a service that queries GitHub to find user information.

`src/main/java/hello/GitHubLookupService.java`
[source,java]
----
include::complete/src/main/java/hello/GitHubLookupService.java[]
----
    
The `GitHubLookupService` class uses Spring's `RestTemplate` to invoke a remote REST point
(api.github.com/users/), and then convert the answer into a `User` object.

The class is marked with the `@Service` annotation, making it a candidate for Spring's component scanning to detect it and add it to the link:/understanding/application-context[application context].

The `findUser` method is flagged with Spring's `@Async` annotation, indicating it will run on a separate thread. The method's return type is {Future}[`Future<User>`] instead of `User`, a requirement for any asynchronous service. This code uses the concrete implementation of `AsyncResult` to wrap the results of the GitHub query.

NOTE: Creating a local instance of the `GitHubLookupService` class does NOT allow the `findUser` method to run asynchronously. It must be created inside a `@Configuration` class or picked up by `@ComponentScan`.

The timing for GitHub's API can vary. To demonstrate the benefits later in this guide, an extra delay of one second has been added to this service.

== Make the application executable

To run a sample, you can create an executable jar. Spring's `@Async` annotation works with web apps, but you don't need all the extra steps of setting up a web container to see its benefits.


`src/main/java/hello/Application.java`
[source,java]
----
include::complete/src/main/java/hello/Application.java[]
----

`@SpringBootApplication` is a convenience annotation that adds all of the following:
    
- `@Configuration` tags the class as a source of bean definitions for the application context.
- `@EnableAutoConfiguration` tells Spring Boot to start adding beans based on classpath settings, other beans, and various property settings.
- Normally you would add `@EnableWebMvc` for a Spring MVC app, but Spring Boot adds it automatically when it sees **spring-webmvc** on the classpath. This flags the application as a web application and activates key behaviors such as setting up a `DispatcherServlet`.
- `@ComponentScan` tells Spring to look for other components, configurations, and services in the the `hello` package.

The `main()` method uses Spring Boot's `SpringApplication.run()` method to launch an application. Did you notice that there wasn't a single line of XML? No **web.xml** file either. This web application is 100% pure Java and you didn't have to deal with configuring any plumbing or infrastructure.

The {EnableAsync}[`@EnableAsync`] annotation switches on Spring's ability to run `@Async` methods in a background thread pool.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_subhead.adoc[]
include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/build_an_executable_jar_with_both.adoc[]


Logging output is displayed, showing each query to GitHub. Each `Future` result is monitored until available, so when they are all done, the log will print out the results along with the total amount of elapsed time.

....
Looking up PivotalSoftware
Looking up Spring-Projects
Looking up CloudFoundry
Elapsed time: 1855
User [name=Pivotal Software, Inc., blog=http://pivotal.io]
User [name=Cloud Foundry, blog=https://www.cloudfoundry.org/]
User [name=Spring, blog=http://spring.io/projects]
....

To compare how long this takes without the asynchronous feature, try commenting out the `@Async` annotation and run the service again. The total elapsed time should increase noticeably because each query takes at least a second.

Essentially, the longer the task takes and the more tasks are invoked simultaneously, the more benefit you will see with making things asynchronous. The trade off is handling the `Future` interface. It adds a layer of indirection because you are no longer dealing directly with the results, but must instead poll for them. If multiple method calls were previously chained together in a synchronous fashion, converting to an asynchronous approach may require synchronizing results. But this extra work may be necessary if asynchronous method calls solves a critical scaling issue.


== Summary

Congratulations! You've just developed an asynchronous service that lets you scale multiple calls at once.



include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]

